spring:
  thymeleaf:
    mode: HTML
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456asd
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  file:
    path: log/blog.log
  level:
    root: warn
    com.cst: debug

comment.avatar: /images/avatar.png
server:
  port: 80